### ISSUE TITLE
Data\File::read() not compatible with FileSystem\File::read()

### ISSUE THREAD

**Issue by distantnative** [k-next/data#1]
```php
PHP Fatal error:  Declaration of Kirby\Data\File::read(): array must be compatible with Kirby\FileSystem\File::read(): string in …/k-next/data/src/Data/File.php on line 17
```

**Comment by distantnative** [comment]
Not sure if we should remove the type declarations in that favor?

**Comment by bastianallgeier** [comment]
Hm, this is not failing on PHP 7. But only on 7.1 as it seems. I think we don't have any other chance than removing the declaration.

**Comment by distantnative** [comment]
Oh yea, I forgot to mention that I was also testing on 7.1...
I thought about just using different methods names in Data\File, but then we would still have `read()` and `write()` inherited from the FileSystem\File class which would be even more confusing.

**Comment by bastianallgeier** [comment]
The type declarations are a great way to keep the code more consistent and reliable, but I think we are fine as long as we keep everything tested. @lukasbestle what do you think about this? I feel like this is a typical Lukas question? :P

**Comment by lukasbestle** [comment]
I'm pretty sure we should keep the type declarations. If we need to remove them because of compatibility issues, we are doing something wrong.

I think we have these two options:

- Don't inherit the FileSystem\File class (what are the advantages of having the FileSystem\File methods in the Data\File class anyway? The Data\File class is pretty specific and I don't think you would often need other file methods.)
- Use different method names (pretty confusing)

Just overwriting the methods with something completely different isn't that smart in my opinion as extended classes are expected to always be compatible with their underlying parent classes in PHP.

**Comment by bastianallgeier** [comment]
I thought there would be an advantage to have full access to all file methods for data files, but we can definitely reevaluate this. If the Data class is not an extension, but only using the File class as a helper to read and write, I agree that we should keep the declarations on the original File class.

**Comment by lukasbestle** [comment]
Well, I think the same: Having the file methods in the data class is a nice touch, but having it separated to avoid introducing compatibility issues is worth more in my opinion.
